### ISSUE TITLE
发送微信消息返回值IsSuccess处理存在BUG

### ISSUE THREAD

**Issue by andywu188** [Bryan-Cyf/EasyNotice#10]
以下是企业微信返回的消息：
{"errcode":0,"errmsg":"ok"}

但是在EasyNoticeSendResponse类中，
public bool IsSuccess => string.IsNullOrEmpty(ErrMsg);

判断errmsg是否为空表示成功，这明显errmsg不是空的，最终导致返回结果失败，实际是成功的

**Comment by andywu188** [comment]
解决办法是各消息组件使用自己的响应消息类，最后再转换为EasyNoticeSendResponse类

**Comment by Bryan-Cyf** [comment]
感谢提交PR
