### ISSUE TITLE
引入飞书消息通知后，启动不了。

### ISSUE THREAD

**Issue by guduyingkod** [Bryan-Cyf/EasyNotice#5]
报错信息定位到：FeishuOptions
错误信息如下：
`
Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: Microsoft.Extensions.Hosting.IHostedService Lifetime: Singleton ImplementationType: Mall.Marketing.MqQueues.LikeEventFeishuNoticeQueue': Cannot consume scoped service 'Microsoft.Extensions.Options.IOptionsSnapshot`1[EasyNotice.FeishuOptions]' from singleton 'Microsoft.Extensions.Hosting.IHostedService'.)
`
代码配置如下图：
![image](https://github.com/Bryan-Cyf/EasyNotice/assets/112997197/73e8b0ee-2b28-4e45-ac22-3c7046140b9e)
环境是.Net 6。
请大佬帮忙看下，感谢！

**Comment by Bryan-Cyf** [comment]
感谢你将问题提出，这边已经修复，你将包升级到2.0.1以上版本即可

**Comment by Bryan-Cyf** [comment]
> 报错信息定位到：FeishuOptions 错误信息如下： ` Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: Microsoft.Extensions.Hosting.IHostedService Lifetime: Singleton ImplementationType: Mall.Marketing.MqQueues.LikeEventFeishuNoticeQueue': Cannot consume scoped service 'Microsoft.Extensions.Options.IOptionsSnapshot`1[EasyNotice.FeishuOptions]' from singleton 'Microsoft.Extensions.Hosting.IHostedService'.) ` 代码配置如下图： ![image](https://user-images.githubusercontent.com/112997197/239507745-73e8b0ee-2b28-4e45-ac22-3c7046140b9e.png) 环境是.Net 6。 请大佬帮忙看下，感谢！


感谢你将问题提出，这边已经修复，你将包升级到2.0.1以上版本即可

**Comment by guduyingkod** [comment]
谢谢，更新后正常运行了！
